### ISSUE TITLE
Okteto Install keeps redownload and reinstall

### ISSUE THREAD

**Issue by arash-bizcover** [okteto/remote-kubernetes#117] opened 2020-08-30 12:41 UTC
**Describe the bug**
`Okteto Install` command keeps redownloading and reinstalling the same.

**To Reproduce**
1. ctrl + shitf + p
 
2. Okteto Install

3. Okteto Install

**Expected behavior**
Second time we run Okteto Install, it should check version (maybe +checksum) quickly without re-downloading and echo back already installed or similar.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
-  VSCode: 1.48.2

**Comment by rberrelleza** [comment] 2020-08-30 16:59
Thanks for the issue @arash-bizcover . The intention of the `okteto install` is exactly that, to 'force install' okteto in case you don't have it or if it's corrupted. 

I'm interested in learning more about your use case for this. Do you run the command lot? What for?

**Comment by arash-bizcover** [comment] 2020-09-02 00:31
🙂 not any extraordinary use case, was assuming running this command should only install if the checksum is different (corrupted) or a new update is available.
Please feel free to close the issue, if that is by design then.

**Comment by rberrelleza** [comment] 2020-11-03 20:55
closing since it's by design.

**Closed by rberrelleza** 2020-11-03 20:55 UTC
