### ISSUE TITLE
Connecting to the remote on Fedora 33 fails with publickey error

### ISSUE THREAD

**Issue by RedRoserade** [okteto/remote-kubernetes#135] opened 2021-03-25 10:47 UTC
**Describe the bug**
On Fedora 33, the configured SSH host for the Okteto remote will not connect via VSCode because the SSH key is rejected.

Running the command `ssh <okteto-host-name> -vvvv` shows output like the following:

```
debug1: Offering public key: /home/USER/.okteto/id_rsa_okteto RSA 
SHA256:wUa7qj5C853m..................63jYMO31+CpydNU explicit
debug1: send_pubkey_test: no mutual signature algorithm
```

The problem, according to https://confluence.atlassian.com/bitbucketserverkb/ssh-rsa-key-rejected-with-message-no-mutual-signature-algorithm-1026057701.html, is that `ssh-rsa` keys are now rejected by default.

A workaround is to add `PubkeyAcceptedKeyTypes +ssh-rsa` to the host's config. A fix is to generate the key with a different algorithm.

In fact, running the command 

```
ssh-keygen -t ed25519 -C "" -f id_rsa_okteto
```

On `${HOME}/.okteto` generates a valid SSH key that seems to give no problems.

**To Reproduce**
1. Create a remote Okteto environment manifest
2. Use `Okteto: Up` from VSCode's command palette
3. Wait for the container to build
4. Wait for the SSH window to connect
5. VSCode complains that `publickey` authentication was denied
6. Try connecting via `ssh <okteto-remote-name>`

**Expected behavior**
The new window should connect to the SSH remote host.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Fedora 33

**Comment by rberrelleza** [comment] 2021-03-25 18:55
Thanks for the thorough analysis @RedRoserade ! so, do you think if we generate ed25519 keys, that should fix the issue for everyone? (have to check if windows supports that, but my guess is that it should).

**Comment by RedRoserade** [comment] 2021-03-25 19:24
I think it should, though I cannot be sure, only testing would tell. According to the Arch Wiki, ed25519 keys have been supported since OpenSSH 6.5, which dates back to 2014: https://wiki.archlinux.org/index.php/SSH_keys#Ed25519

The same algorithm is documented in Windows Server documentation, so there's a good chance it works there too: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement

And, since these keys are used only for connecting to remote Okteto instances, it should be fine.

**Comment by rberrelleza** [comment] 2021-03-26 00:05
Sounds like ed25519 is a good candidate for them.  The root cause of the issue is on okteto/okteto, once https://github.com/okteto/okteto/pull/1351 is merged and released, we'll update it on the plugin.

**Comment by rberrelleza** [comment] 2021-04-02 20:31
We had some issues with compatibility with ed25519, so we'll start by adding the PubkeyAcceptedKeyTypes key first, while we work on supporting ed25519.

**Comment by RedRoserade** [comment] 2021-04-05 12:57
I see, I was concerned that could happen. I'd say that the workaround will be good enough for now, too.

**Comment by rberrelleza** [comment] 2021-04-05 17:01
@RedRoserade could you try the build from master to make sure if solves the issue? The extension has a setting to pass a binary instead of using the expected version. You can build it yourself, or use https://downloads.okteto.com/cli/master/okteto-Linux-x86_64

**Comment by RedRoserade** [comment] 2021-04-05 17:07
@rberrelleza Sure, I will try it tomorrow on my work machine and I'll add my feedback here.

**Comment by RedRoserade** [comment] 2021-04-06 09:41
@rberrelleza It works; after compiling locally, deleting previous ssh keys, and changing the paths, this is what I get on my ssh config:

```➜  okteto git:(master) ✗ cat ~/.ssh/config
# entry generated by okteto
Host cps-api.okteto
  ForwardAgent yes
  PubkeyAcceptedKeyTypes +ssh-rsa
  HostName localhost
  Port 36043
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  IdentityFile "/home/$USER/.okteto/id_rsa_okteto"
```

And most importantly, VSCode connects.

Thank you!

**Comment by rberrelleza** [comment] 2021-04-06 16:14
thanks for checking, I'll update the extension as soon as possible

**Closed** 2021-04-07 01:09 UTC

**Comment by rberrelleza** [comment] 2021-04-07 01:59
version 0.2.1 has the fix, if you want to try it out @RedRoserade

**Comment by RedRoserade** [comment] 2021-04-07 18:14
Already have, it works well. Thanks!
